apiVersion: apps/v1
kind: Deployment 
metadata:
  name: runners
  labels:
    app: runners
spec:
  replicas: 1
  selector:
    matchLabels:
      app: runners
  template:
    metadata:
      labels:
        app: runners
    spec:
      containers:
      - name: runner
        image: runner:latest
        imagePullPolicy: Never
        env:
        - name: GITHUB_REPO
          value: https://github.com/xxxxx
        - name: GITHUB_PAT
          valueFrom:
            secretKeyRef:
              name: github-token
              key: token
              optional: false 
        lifecycle:
          preStop:
            exec:
              command: ["/bin/bash","-c","./config.sh remove --pat ${GITHUB_PAT}"]

